# Generated by Django 2.1.5 on 2019-01-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('small_img_path', models.ImageField(blank=True, upload_to='product_small_img', verbose_name='Миниатюра')),
                ('big_img_path', models.ImageField(blank=True, upload_to='product_big_img', verbose_name='Изображение')),
                ('category', models.ManyToManyField(blank=True, to='mainapp.Category', verbose_name='Категория')),
            ],
        ),
    ]
