# Generated by Django 2.1.5 on 2019-01-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogmenu',
            name='link',
        ),
    ]
