# Generated by Django 2.1.5 on 2019-02-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190203_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='catalogmenu',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='newmenu',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Категория'),
        ),
    ]
