# Generated by Django 2.1.5 on 2019-02-03 17:58

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to=authapp.models.image_path),
        ),
    ]
